### ISSUE TITLE
Pull request issue

### ISSUE THREAD

**Issue by Umaraziz99** [economicanalysiswithmatrices/zombie-story#39]
Initially I tried to approve someone else's pull request however it didn't work, so I carried on doing the rest of the steps. I made my changes to the story and submitted my pull request. After doing so, I realised that I didn't name my pull request with my Surrey username and cancelled my pull request. Also I was now able to approve the other pull request and on doing so this changed the zombiestory.txt file. I am unsure on how to start again using my surrey username branch and the updated zombiestory.txt file.

**Comment by meleantonio** [comment]
I took care of it, no worries
