### ISSUE TITLE
Solution Template

### ISSUE THREAD

**Issue by morooney99** [economicanalysiswithmatrices/zombie-story#7]
Dear Antonio,

I have added a new line to Github and copied and pasted it into matlab grader between "", what did you mean when you said solution template in Matlab grader, where can I find this?

**Comment by meleantonio** [comment]
Sorry @morooney99 there was a mistake in the Matlab Grader. I have fixed it now. You should see the following code:
```matlab
% Go to this link: https://github.com/economicanalysiswithmatrices/zombie-story
% follow the instructions in the README file.
% then copy what you have added in between the " ". Click Submit.
a = "Copy/paste here the paragraph that you have added to the story."
b = isstring(a)
disp(sprintf(a))
```
Just copy your piece into the " " in a. Sorry about this.

**Comment by morooney99** [comment]
Thank you, it has worked now.
