### ISSUE TITLE
Pushing to origin

### ISSUE THREAD

**Issue by Abzjodi** [economicanalysiswithmatrices/zombie-story#9]
Hello Antonio,

When I commit using my branch, the previous students line does not appear on my branch and only appears on the master branch, after I had fetched from the origin. Why is this the case? As such when I was committing Github said there was a merge error and it was probably due to this. It worked when I committed straight to master. 

Thanks,
Abbas

**Comment by meleantonio** [comment]
what  is your branch? can you give me the name please?

**Comment by Abzjodi** [comment]
aj00629

**Comment by Abzjodi** [comment]
![git1](https://user-images.githubusercontent.com/44603969/48352920-fcbbb900-e685-11e8-8964-ac492c8598ef.PNG)
![git2](https://user-images.githubusercontent.com/44603969/48352922-004f4000-e686-11e8-9278-2d16a3a904c3.PNG)
I am now getting this message from github although I haven't pushed my branch, I pushed the master branch with my addition to the story. I don't know why that has appeared, but as you can see, it still says merge error.

Thanks

**Comment by meleantonio** [comment]
This is the problem: when you created your branch, someone added a line in the story (let me call it line A), and then merged it into the master branch. When you try to merge your branch, Github sees that your version misses line A, and therefore tells you it can't automatically merge. This is not a mistake! It just needs a bit more work. If cases like this happen, I will solve it myself, no worries. You can still create the pull request, but it needs to be approved by me.

**Comment by Abzjodi** [comment]
I have created a pull request, but it says there are 4 commits I would like to merge (although I believe I reverted two of them due to the aforementioned errors). I'm not sure if I've done the correct thing, please let me know if there is something I need to change.

**Comment by meleantonio** [comment]
No worries, I've taken care of this. It is ok.
